from rocketmq.client import Producer, Message
producer = Producer('PID-XXX')
# producer.set_namesrv_domain('http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet')
producer.set_namesrv_addr('10.1.160.162:9876')
producer.start()
msg = Message('YOUR-TOPIC')
msg.set_keys('a')
msg.set_tags('b')
msg.set_body('c')
ret = producer.send_sync(msg)
print(ret.status, ret.msg_id, ret.offset)
producer.shutdown()